### ISSUE TITLE
Displaying an image with `∆.Image` (`w_img`) shows a 1D row of monochrome pixels rather than a 2D coloured image

### ISSUE THREAD

**Issue by ErnWong** [Co-dfns/Co-dfns#493]
Hi. I saw a demo of the data exploration tools in this [talk](https://youtu.be/IYh5GX9H92c?t=2058) and wanted to try it out (in particular `∆.Image` and `∆.Display`). However, passing a 2d array or an appropriately sized 3d array seem to result in a single column of monochrome pixels as shown below:

```apl
ns←⎕NS⍬
ns.art←{↑(0 0 0 1) (0 0 1 1) (0 1 0 0) (1 1 ⍵ 1)}
]CODFNS.Compile ns cdns
cdns.∆.Rtm∆Init 'cdns'
'Window title' {_←⍺ cdns.∆.Image cdns.art ⍵ ⋄ ~⍵} cdns.∆.Display {0} 1
```

![Screenshot_20230201_211455](https://user-images.githubusercontent.com/2609018/215987577-9be534ce-a479-478e-8412-8836a3612c0d.png)

I wonder if it's a regression introduced in https://github.com/Co-dfns/Co-dfns/issues/303 in commit https://github.com/Co-dfns/Co-dfns/commit/a7dee2ac34834fa89eb6308d46a66ef1d23d62ed#diff-89d494ac3d38a7a6c7f361870646b9b6a55e265c18a6d31528d75c1de2d5e2f9 (although I only inspected the definition of `cpda`. I haven't actually tried running before and after that commit so I could be wrong).

### Environment

- NixOS 22.11
- Dyalog 18.2.45405
- Co-dfns 4.1.2
- ArrayFire 3.7.3

Full code to reproduce the issue:

https://github.com/ErnWong/apl-hello-world/tree/1cbd4d7afec271266014ca0e46a64515e01488fa

```bash
nix develop github:ErnWong/apl-hello-world?rev=1cbd4d7afec271266014ca0e46a64515e01488fa --command bash -c "nix run github:ErnWong/apl-hello-world?rev=1cbd4d7afec271266014ca0e46a64515e01488fa"
```

Thanks! I appreciate your work on this project.

**Comment by arcfide** [comment]
Thanks for the report! This was a regression due to our removal of shape information in the underlying data representations used by ArrayFire, which caused the API to think that all of the arrays were just flat single column arrays. I've released v4.1.3 with a patch that should fix this issue for you.
