### ISSUE TITLE
New Benchmarks for the Compiler

### ISSUE THREAD

**Issue by arcfide** [Co-dfns/Co-dfns#76]
We need a set of new benchmarks. Right now we only have the one, and that isn't good enough.

**Comment by arcfide** [comment]
There is the GenoKey code which is the obvious next solution once the compiler is more feature-complete. However, Martin Elsman indicates that there is an APL benchmark suite somewhere on GitHub.

**Comment by arcfide** [comment]
I spoke with @melsman the other day extensively about the benchmarks that he is using. I think that they are all very close to being runnable on Co-dfns, but I also found that many of them are coded in a very inefficient way for the compiler, which would lead to most of the tests being tests of the interpreter overhead instead of the actual runtime performance of Dyalog. I am spending some time getting these cleaned up.

**Comment by arcfide** [comment]
The APL benchmarks are at https://github.com/dybber/aplbench

**Comment by arcfide** [comment]
The Sobol Pi benchmark as I documented in an email is severely inefficient at the moment from the interpreter standpoint. Compilers are able to mitigate this inefficiency. Adjusting the Sobol Pi benchmark leads to a 78× improvement in performance, with more to be had. Here is the improved `pi` function:

    pi ← {
      gc←⌽⍉{1↓⍵≠¯1⊖⍵}(31⍴2)⊤1+⍳⍵
      s←(2⊥≠/(32⍴2)⊤gc×⍤1⍤1 2⊢2 30⍴#.DIR∆VEC)÷2*30
      4×(+/1>(+/s*2)*÷2)÷⍵
    }

**Comment by arcfide** [comment]
Youngsung Kim has sent me an NCAR kernel from a weather simulation they are doing. This is an MG2 kernel used in their computation. It accounts for around 10% of their total performance. Found here:

https://proxy.subversion.ucar.edu/pubasap/kernels/trunk/MG2_CAM5_INTEL/

This is a real world application that is in active use and represents a compelling "market" for APL compilers, IMO. I think it would be worth putting effort into making this work and making it work fast.

**Comment by melsman** [comment]
Hi Aaron,

Thanks! Let's see what we can do about that. It is somewhat unsatisfactory
that the APL interpreters enforce one to inline manually the code for bit
manipulations...

@Martin Dybdal: I talked to Aaron about the Sobol Pi benchmark, and he has
contributed with the code below.  Notice the use of decode (and encode)
and, in particular, the use of ≠ instead of xor...

Best,

Martin

---------- Forwarded message ----------

**Comment by arcfide** [comment]
I'll reiterate a few remarks here that we discussed in person just for the record. Unlike some languages, Dyalog APL does have explicit means of dealing with bitvectors as a native type. Thus, it is not necessary to create additional abstractions such as the original `xor` function, since `≠` *is* the `xor` function. On the other hand, it's definitely one of the benefits of a compiler that we can inline and fuse code that would otherwise overload or stress the interpreter's evaluator.

**Comment by arcfide** [comment]
In case @dybber has not seen this, I am linking his username directly.

**Comment by arcfide** [comment]
@mkromberg may also find this all interesting.

**Comment by arcfide** [comment]
We also have ready made hashing code that would make good benchmarks, especially as we get character type support.

**Comment by arcfide** [comment]
I have linked in the 5 additional benchmarks that I think should be the primary focus of this release cycle.

**Comment by arcfide** [comment]
Sufficient other stories exist now that we can close this.
